#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: smailkoz/torrserver
  # -- image tag
  tag: 1.0.111
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables. See more environment variables in the [torrserver documentation](https://torrserver.org/docs).
# @default -- See below
env:
  # -- Set the container timezone
  TZ: UTC
  # -- Set data dir
  TS_CONF_PATH: /data
  # -- Set torrent-tiles dir
  TS_TORR_DIRL: /data/torrents
# -- Allowing to use DLNA
hostNetwork: true
# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 8090

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  data:
    enabled: false
    mountPath: /data
